-- public.geo_polygon definition

-- Drop table

-- DROP TABLE geo_polygon;

CREATE TABLE geo_polygon (
                             id_gp int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                             uuid_gp uuid NOT NULL,
                             zone_gp varchar NOT NULL,
                             registred_gp timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             updated_gp timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             active_gp bool DEFAULT true NOT NULL,
                             CONSTRAINT geo_polygon_pk PRIMARY KEY (id_gp)
);

-- Permissions

ALTER TABLE geo_polygon OWNER TO postgres;
GRANT ALL ON TABLE geo_polygon TO postgres;


-- public.polygon_vertex definition

-- Drop table

-- DROP TABLE polygon_vertex;

CREATE TABLE polygon_vertex (
                                id_pv int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                uuid_pv uuid NOT NULL,
                                geo_polygon_id int8 NOT NULL,
                                orden_pv int8 NOT NULL,
                                latitude_pv float8 NOT NULL,
                                length_pv float8 NOT NULL,
                                registred_pv timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                updated_pv timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                active_pv bool DEFAULT true NOT NULL,
                                CONSTRAINT polygon_vertices_pk PRIMARY KEY (id_pv),
                                CONSTRAINT polygon_vertices_geo_polygon_fk FOREIGN KEY (geo_polygon_id) REFERENCES geo_polygon(id_gp)
);

-- Permissions

ALTER TABLE polygon_vertex OWNER TO postgres;
GRANT ALL ON TABLE polygon_vertex TO postgres;


-- public.tabulator definition

-- Drop table

-- DROP TABLE tabulator;

CREATE TABLE tabulator (
                           id_tab int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                           uuid_tab uuid NOT NULL,
                           originpolygon_id int8 NOT NULL,
                           destinationpolygon_id int8 NOT NULL,
                           cost_tab float8 NOT NULL,
                           registred_tab timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           updated_tab timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           active_tab bool DEFAULT true NOT NULL,
                           CONSTRAINT tabulator_pk PRIMARY KEY (id_tab),
                           CONSTRAINT tabulator_geo_polygon_fk FOREIGN KEY (originpolygon_id) REFERENCES geo_polygon(id_gp),
                           CONSTRAINT tabulator_geo_polygon_fk_1 FOREIGN KEY (destinationpolygon_id) REFERENCES geo_polygon(id_gp)
);

-- Permissions

ALTER TABLE tabulator OWNER TO postgres;
GRANT ALL ON TABLE tabulator TO postgres;